module;
#include <algorithm>
#include <cctype>
#include <expected>
#include <filesystem>
#include <format>
#include <fstream>
#include <ios>
#include <iterator>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <system_error>
#include <vector>
module cup.cmd;

import cup.ui;
import cup.scaffold;

namespace cup::cmd {
namespace {

constexpr std::string_view kAptMarker = "# cup-apt:";

constexpr std::string_view kGeneratedDockerfileHeader =
    "# Generated by cup — do not edit by hand.\n"
    "# This is the project's default build image. cup keeps its FROM base and the\n"
    "# apt packages of registered third-party dependencies in sync; `cup docker build`\n"
    "# versions and tags it, and `cup compiler verify` compiles the project in it.\n#\n";

// third_party_file is where registrations are recorded for the project's
// build tool: third_party/CMakeLists.txt for CMake, third_party/third_party.mk
// for Make. apt_packages scans whichever, so Docker image sync works for both.
std::filesystem::path third_party_file(const project::Project& proj) {
    if (proj.uses_make()) {
        return proj.path("third_party", "third_party.mk");
    }
    return proj.path("third_party", "CMakeLists.txt");
}

std::string join(std::span<const std::string> parts, std::string_view sep) {
    std::string out;
    for (std::size_t i = 0; i < parts.size(); ++i) {
        if (i > 0) {
            out += sep;
        }
        out += parts[i];
    }
    return out;
}

std::vector<std::string_view> split_fields(std::string_view s) {
    std::vector<std::string_view> fields;
    std::size_t i = 0;
    while (i < s.size()) {
        while (i < s.size() && std::isspace(static_cast<unsigned char>(s[i]))) {
            ++i;
        }
        const std::size_t start = i;
        while (i < s.size() && !std::isspace(static_cast<unsigned char>(s[i]))) {
            ++i;
        }
        if (i > start) {
            fields.push_back(s.substr(start, i - start));
        }
    }
    return fields;
}

std::optional<std::string> read_whole_file(const std::filesystem::path& path) {
    std::ifstream in(path, std::ios::binary);
    if (!in) {
        return std::nullopt;
    }
    return std::string(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
}

}  // namespace

std::filesystem::path docker_image_dir(const project::Project& proj, std::string_view name) {
    return proj.path("docker", name);
}

std::filesystem::path dockerfile_path(const project::Project& proj, std::string_view name) {
    return docker_image_dir(proj, name) / "Dockerfile";
}

std::vector<std::string> apt_packages(const project::Project& proj) {
    const auto lines = scaffold::read_file_lines(third_party_file(proj));
    if (!lines.has_value()) {
        return {};
    }
    std::vector<std::string> pkgs;
    std::vector<std::string> seen;
    for (const auto& raw : *lines) {
        const auto idx = raw.find(kAptMarker);
        if (idx == std::string::npos) {
            continue;
        }
        for (const auto field : split_fields(std::string_view(raw).substr(idx + kAptMarker.size()))) {
            const std::string pkg(field);
            if (std::find(seen.begin(), seen.end(), pkg) == seen.end()) {
                seen.push_back(pkg);
                pkgs.push_back(pkg);
            }
        }
    }
    return pkgs;
}

std::string render_build_dockerfile(std::string_view base, std::span<const std::string> pkgs) {
    std::string out(kGeneratedDockerfileHeader);
    out += "FROM ";
    out += base;
    out += "\n";
    if (!pkgs.empty()) {
        out += "\nRUN apt-get update \\\n";
        out += "    && apt-get install -y --no-install-recommends \\\n";
        for (const auto& p : pkgs) {
            out += "        ";
            out += p;
            out += " \\\n";
        }
        out += "    && rm -rf /var/lib/apt/lists/*\n";
    }
    return out;
}

std::expected<void, error::Error> sync_default_build_image(const project::Project& proj) {
    const auto* def = proj.config.docker.default_image();
    if (def == nullptr) {
        return {};
    }
    const auto pkgs = apt_packages(proj);
    const std::string content = render_build_dockerfile(def->base, pkgs);
    const std::filesystem::path path = dockerfile_path(proj, def->name);

    if (const auto old = read_whole_file(path); old.has_value() && *old == content) {
        return {};
    }

    std::error_code ec;
    std::filesystem::create_directories(path.parent_path(), ec);
    if (ec) {
        return std::unexpected(
            error::Error(std::format("creating {}: {}", path.parent_path().string(), ec.message())));
    }
    std::ofstream out(path, std::ios::binary | std::ios::trunc);
    out << content;
    if (!out) {
        return std::unexpected(error::Error(std::format("writing {}", path.string())));
    }

    const std::string label = (std::filesystem::path("docker") / def->name / "Dockerfile").string();
    if (!pkgs.empty()) {
        ui::updated(std::format("{}  (apt: {})", label, join(pkgs, " ")));
    } else {
        ui::updated(label);
    }
    return {};
}

std::expected<std::string, error::Error> choose_image_tag(std::string_view repo) {
    auto tags = scaffold::docker_hub_tags(repo);
    if (!tags.has_value() || tags->values.empty()) {
        ui::skipped(std::format("could not list tags for {} — enter one manually", repo));
        return ui::text("image tag?", "latest", scaffold::validate_non_empty);
    }
    std::vector<std::string> list = tags->values;
    if (list.size() > 20) {
        list.resize(20);
    }
    return ui::select_one(std::format("image tag for {}?", repo), list, list[0]);
}

std::expected<std::string, error::Error> choose_base_image() {
    auto repo = ui::text("base image repository? (e.g. gcc, debian, silkeh/clang)", "",
                         scaffold::validate_non_empty);
    if (!repo.has_value()) {
        return std::unexpected(std::move(repo).error());
    }
    auto tag = choose_image_tag(*repo);
    if (!tag.has_value()) {
        return std::unexpected(std::move(tag).error());
    }
    return *repo + ":" + *tag;
}

}
