package cmd

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"cup/internal/project"
	"cup/internal/scaffold"
	"cup/internal/ui"
)

// RunDocker is `cup docker`: manage the project's build images, each living at
// docker/<name>/Dockerfile and versioned in cup.toml's [docker] table.
//
//	cup docker new            scaffold a new build image (prompts name + base)
//	cup docker build [name]   build image(s), bumping the version on a change
//	cup docker push  [name]   push image(s) to the configured registry
//
// The default build image (created by `cup new`) additionally tracks the
// project's apt third-party dependencies: cup regenerates its Dockerfile whenever
// they change, so the image updates itself.
func RunDocker(args []string) error {
	proj, err := project.Find()
	if err != nil {
		return err
	}
	if len(args) == 0 {
		return fmt.Errorf("usage: cup docker <new|build|push> [name]")
	}
	switch args[0] {
	case "new":
		return dockerNew(proj)
	case "build":
		return dockerBuild(proj, args[1:])
	case "push":
		return dockerPush(proj, args[1:])
	default:
		return fmt.Errorf("unknown `cup docker` subcommand %q (use: new, build, push)", args[0])
	}
}

// --- generated Dockerfile --------------------------------------------------

const generatedDockerfileHeader = "# Generated by cup — do not edit by hand.\n" +
	"# This is the project's default build image. cup keeps its FROM base and the\n" +
	"# apt packages of registered third-party dependencies in sync; `cup docker build`\n" +
	"# versions and tags it, and `cup compiler verify` compiles the project in it.\n#\n"

// renderBuildDockerfile builds the default image's Dockerfile: a bare `FROM base`
// plus, when the project registers apt dependencies, a layer that installs them.
func renderBuildDockerfile(base string, pkgs []string) string {
	var b strings.Builder
	b.WriteString(generatedDockerfileHeader)
	b.WriteString("FROM " + base + "\n")
	if len(pkgs) > 0 {
		b.WriteString("\nRUN apt-get update \\\n")
		b.WriteString("    && apt-get install -y --no-install-recommends \\\n")
		for _, p := range pkgs {
			b.WriteString("        " + p + " \\\n")
		}
		b.WriteString("    && rm -rf /var/lib/apt/lists/*\n")
	}
	return b.String()
}

// syncDefaultBuildImage regenerates the default build image's Dockerfile from its
// base and the currently registered apt packages, so the image stays in step with
// the project's third parties. It is a no-op when the project has no default image
// (older projects, or `cup register` run before a default image exists), and it
// avoids rewriting an unchanged file so builds only bump the version on a real
// change.
func syncDefaultBuildImage(proj *project.Project) error {
	def, ok := proj.Config.Docker.DefaultImage()
	if !ok {
		return nil
	}
	content := renderBuildDockerfile(def.Base, aptPackages(proj))
	path := dockerfilePath(proj, def.Name)
	if old, err := os.ReadFile(path); err == nil && string(old) == content {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return err
	}
	label := filepath.Join("docker", def.Name, "Dockerfile")
	if pkgs := aptPackages(proj); len(pkgs) > 0 {
		ui.Updated(fmt.Sprintf("%s  (apt: %s)", label, strings.Join(pkgs, " ")))
	} else {
		ui.Updated(label)
	}
	return nil
}

// --- new -------------------------------------------------------------------

// dockerNew scaffolds an additional, user-managed build image: a docker/<name>/
// directory with a starter Dockerfile and a [[docker.image]] entry. Unlike the
// default image, cup does not rewrite this Dockerfile — it is yours to edit.
func dockerNew(proj *project.Project) error {
	name, err := ui.Text("image name?", "", scaffold.ValidateIdent)
	if err != nil {
		return err
	}
	name = strings.ToLower(name)
	if _, exists := proj.Config.Docker.Find(name); exists {
		return fmt.Errorf("an image named %q already exists in this project", name)
	}
	base, err := chooseBaseImage()
	if err != nil {
		return err
	}
	if _, err := scaffold.WriteFile(proj.Root, dockerfilePath(proj, name), "FROM "+base+"\n"); err != nil {
		return err
	}
	proj.Config.Docker.Images = append(proj.Config.Docker.Images,
		project.DockerImage{Name: name, Base: base})
	if err := persistConfig(proj); err != nil {
		return err
	}
	ui.Success("image " + name + " created.")
	ui.Next("cup docker build " + name)
	return nil
}

// chooseBaseImage prompts for a Docker Hub repository and a tag, returning a
// "repo:tag" reference. Tags are fetched live so the user picks a real one;
// offline, it falls back to typing the tag by hand.
func chooseBaseImage() (string, error) {
	repo, err := ui.Text("base image repository? (e.g. gcc, debian, silkeh/clang)", "", scaffold.ValidateNonEmpty)
	if err != nil {
		return "", err
	}
	tag, err := chooseImageTag(repo)
	if err != nil {
		return "", err
	}
	return repo + ":" + tag, nil
}

// chooseImageTag lists repo's Docker Hub tags to pick from, capping the (newest
// first) list so the menu stays usable, and falling back to a free-text entry
// when the tags cannot be fetched.
func chooseImageTag(repo string) (string, error) {
	tags, err := scaffold.DockerHubTags(repo)
	if err != nil || len(tags) == 0 {
		ui.Skipped("could not list tags for " + repo + " — enter one manually")
		return ui.Text("image tag?", "latest", scaffold.ValidateNonEmpty)
	}
	if len(tags) > 20 {
		tags = tags[:20]
	}
	return ui.Select("image tag for "+repo+"?", tags, tags[0])
}

// --- build -----------------------------------------------------------------

// dockerBuild builds the named image, or every image when no name is given,
// bumping each image's version when its Dockerfile content changed since the last
// build. Versions are persisted only once all requested builds succeed.
func dockerBuild(proj *project.Project, args []string) error {
	targets, err := selectImages(proj, args)
	if err != nil {
		return err
	}
	for _, img := range targets {
		if err := buildImage(proj, img); err != nil {
			return err
		}
	}
	return persistConfig(proj)
}

// buildImage regenerates the default image's Dockerfile, then hashes it to decide
// whether the version should advance, and builds the image under the versioned
// and latest tags.
func buildImage(proj *project.Project, img *project.DockerImage) error {
	if img.Default {
		if err := syncDefaultBuildImage(proj); err != nil {
			return err
		}
	}
	path := dockerfilePath(proj, img.Name)
	if !isFile(path) {
		return fmt.Errorf("image %q has no Dockerfile at %s",
			img.Name, filepath.Join("docker", img.Name, "Dockerfile"))
	}
	hash, err := hashFile(path)
	if err != nil {
		return err
	}
	img.Version = nextVersion(img.Version, img.Hash, hash)
	img.Hash = hash
	versioned := imageTag(img.Name, img.Version)
	ui.Running(fmt.Sprintf("building %s from %s", versioned, img.Base))
	return runCommand(proj.Root, "docker", "build",
		"-t", versioned, "-t", img.Name+":latest", dockerImageDir(proj, img.Name))
}

// nextVersion advances an image's version only when its content changed: an
// unchanged, already-built image keeps its number, while a first build or a
// content change increments it.
func nextVersion(cur int, oldHash, newHash string) int {
	if cur > 0 && oldHash == newHash {
		return cur
	}
	return cur + 1
}

// --- push ------------------------------------------------------------------

// dockerPush publishes built image(s) to the configured registry, prompting for
// (and saving) the registry the first time. Each image is retagged under
// <registry>/<name> and pushed at both its version and latest.
func dockerPush(proj *project.Project, args []string) error {
	targets, err := selectImages(proj, args)
	if err != nil {
		return err
	}
	if proj.Config.Docker.Registry == "" {
		reg, err := ui.Text("registry/namespace to push to? (e.g. docker.io/youruser)", "", scaffold.ValidateNonEmpty)
		if err != nil {
			return err
		}
		proj.Config.Docker.Registry = strings.TrimRight(strings.TrimSpace(reg), "/")
		if err := persistConfig(proj); err != nil {
			return err
		}
	}
	reg := proj.Config.Docker.Registry
	for _, img := range targets {
		if img.Version == 0 {
			return fmt.Errorf("image %q has not been built yet — run `cup docker build %s` first", img.Name, img.Name)
		}
		if err := pushImage(proj, reg, img); err != nil {
			return err
		}
	}
	return nil
}

func pushImage(proj *project.Project, reg string, img *project.DockerImage) error {
	for _, tag := range []string{fmt.Sprintf("%d", img.Version), "latest"} {
		local := img.Name + ":" + tag
		remote := reg + "/" + img.Name + ":" + tag
		if err := runCommand(proj.Root, "docker", "tag", local, remote); err != nil {
			return err
		}
		if err := runCommand(proj.Root, "docker", "push", remote); err != nil {
			return err
		}
	}
	return nil
}

// --- helpers ---------------------------------------------------------------

// selectImages resolves the images a build/push acts on: the one named in args,
// or all of them when no name is given. The returned pointers alias the project
// config so version/hash updates persist on WriteConfig.
func selectImages(proj *project.Project, args []string) ([]*project.DockerImage, error) {
	if len(proj.Config.Docker.Images) == 0 {
		return nil, fmt.Errorf("this project defines no docker images (create one with `cup docker new`)")
	}
	if len(args) > 0 && args[0] != "" {
		img, ok := proj.Config.Docker.Find(args[0])
		if !ok {
			return nil, fmt.Errorf("no docker image named %q in this project", args[0])
		}
		return []*project.DockerImage{img}, nil
	}
	out := make([]*project.DockerImage, len(proj.Config.Docker.Images))
	for i := range proj.Config.Docker.Images {
		out[i] = &proj.Config.Docker.Images[i]
	}
	return out, nil
}

func dockerImageDir(proj *project.Project, name string) string {
	return proj.Path("docker", name)
}

func dockerfilePath(proj *project.Project, name string) string {
	return filepath.Join(dockerImageDir(proj, name), "Dockerfile")
}

func imageTag(name string, version int) string {
	return fmt.Sprintf("%s:%d", name, version)
}

// hashFile returns the hex sha256 of a file's contents, cup's fingerprint for
// deciding whether an image's Dockerfile changed since its last build.
func hashFile(path string) (string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:]), nil
}

// persistConfig writes the (mutated) project config back to cup.toml.
func persistConfig(proj *project.Project) error {
	if err := project.WriteConfig(proj.Root, proj.Config); err != nil {
		return err
	}
	ui.Updated(project.Marker)
	return nil
}
