# Generator behind cup_embed_templates(), run via `cmake -P`.
#
# Reads every file under CUP_TEMPLATE_DIR and writes a header + source pair that
# expose the corpus as compile-time std::string_view constants. This is the C++
# replacement for Go's `//go:embed all:files`.
#
# Required cache entries:
#   CUP_TEMPLATE_DIR     root of the template corpus
#   CUP_HEADER_OUT       path of the generated .hpp
#   CUP_SOURCE_OUT       path of the generated .cpp
#   CUP_HEADER_INCLUDE   how the generated source spells its #include of the
#                        header, i.e. the header's path relative to the include
#                        directory the target exposes

cmake_minimum_required(VERSION 3.28)

foreach(var CUP_TEMPLATE_DIR CUP_HEADER_OUT CUP_SOURCE_OUT CUP_HEADER_INCLUDE)
  if(NOT DEFINED ${var})
    message(FATAL_ERROR "GenerateEmbeddedTemplates.cmake: -D ${var}=... is required")
  endif()
endforeach()

# The raw-string delimiter. Template content is embedded verbatim between
# R"<delim>( and )<delim>", so the corpus must never contain the closing sequence.
set(CUP_RAW_DELIM "cuptmpl")

file(GLOB_RECURSE template_files RELATIVE "${CUP_TEMPLATE_DIR}" "${CUP_TEMPLATE_DIR}/*")
list(FILTER template_files EXCLUDE REGEX "(^|/)\\.")   # drop dotfiles
list(SORT template_files)                              # deterministic output

list(LENGTH template_files template_count)
if(template_count EQUAL 0)
  message(FATAL_ERROR "GenerateEmbeddedTemplates.cmake: no templates under ${CUP_TEMPLATE_DIR}")
endif()

set(constants "")
set(table "")
set(index 0)

foreach(rel IN LISTS template_files)
  set(abs "${CUP_TEMPLATE_DIR}/${rel}")
  if(IS_DIRECTORY "${abs}")
    continue()
  endif()

  file(READ "${abs}" content)

  # A template containing the closing delimiter would silently truncate the
  # generated string literal, so refuse rather than emit code that miscompiles.
  string(FIND "${content}" ")${CUP_RAW_DELIM}\"" clash)
  if(NOT clash EQUAL -1)
    message(FATAL_ERROR
      "template ${rel} contains the raw-string terminator )${CUP_RAW_DELIM}\" — "
      "change CUP_RAW_DELIM in cmake/GenerateEmbeddedTemplates.cmake")
  endif()

  string(APPEND constants
    "constexpr std::string_view kContent${index} = R\"${CUP_RAW_DELIM}(${content})${CUP_RAW_DELIM}\";\n")
  string(APPEND table "    {\"${rel}\", kContent${index}},\n")
  math(EXPR index "${index} + 1")
endforeach()

set(header "\
// Generated by cmake/EmbedTemplates.cmake — do not edit.
//
// The cup template corpus, embedded in the binary. This is the C++ counterpart of
// the Go implementation's `//go:embed all:files`: paths are corpus-relative and
// slash-separated (e.g. \"modules/class/source.cppm.tmpl\"), exactly as they are
// on disk under templates/.
#pragma once

#include <optional>
#include <span>
#include <string_view>

namespace cup::templates {

// Entry is one embedded template: its corpus-relative path and its content.
struct Entry {
  std::string_view path;
  std::string_view content;
};

// all returns every embedded template, sorted by path. Directory listings (the
// equivalent of embed.FS's ReadDir) are derived from this by prefix.
[[nodiscard]] std::span<const Entry> all() noexcept;

// read returns the content of the template at path, or nullopt if the corpus has
// no such entry.
[[nodiscard]] std::optional<std::string_view> read(std::string_view path) noexcept;

// exists reports whether the corpus holds a template at path.
[[nodiscard]] bool exists(std::string_view path) noexcept;

}  // namespace cup::templates
")

set(source "\
// Generated by cmake/EmbedTemplates.cmake — do not edit.
//
// ${index} templates embedded from ${CUP_TEMPLATE_DIR}.
//
// Deliberately a plain translation unit rather than a module interface: the
// corpus is a few hundred KB of string data, and keeping it out of any BMI keeps
// module builds small and sidesteps the large-BMI corners of GCC 14. The cup.tmpl
// module includes the generated header in its global module fragment.
#include <${CUP_HEADER_INCLUDE}>

#include <algorithm>

namespace cup::templates {
namespace {

${constants}
constexpr Entry kEntries[] = {
${table}};

}  // namespace

std::span<const Entry> all() noexcept { return kEntries; }

std::optional<std::string_view> read(std::string_view path) noexcept {
  const auto it = std::find_if(std::begin(kEntries), std::end(kEntries),
                               [path](const Entry& e) { return e.path == path; });
  if (it == std::end(kEntries)) {
    return std::nullopt;
  }
  return it->content;
}

bool exists(std::string_view path) noexcept { return read(path).has_value(); }

}  // namespace cup::templates
")

# Write through a temporary and copy_if_different so an unchanged corpus does not
# retrigger every dependent compile.
file(WRITE "${CUP_HEADER_OUT}.tmp" "${header}")
file(WRITE "${CUP_SOURCE_OUT}.tmp" "${source}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different
                "${CUP_HEADER_OUT}.tmp" "${CUP_HEADER_OUT}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different
                "${CUP_SOURCE_OUT}.tmp" "${CUP_SOURCE_OUT}")
file(REMOVE "${CUP_HEADER_OUT}.tmp" "${CUP_SOURCE_OUT}.tmp")

message(STATUS "cup: embedded ${index} templates from ${CUP_TEMPLATE_DIR}")
