module;
#include <algorithm>
#include <array>
#include <cctype>
#include <cstdint>
#include <expected>
#include <filesystem>
#include <format>
#include <fstream>
#include <ios>
#include <iterator>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <system_error>
#include <vector>
module cup.cmd;

import cup.ui;
import cup.scaffold;

namespace cup::cmd {
namespace {

constexpr std::string_view kAptMarker = "# cup-apt:";

constexpr std::string_view kGeneratedDockerfileHeader =
    "# Generated by cup — do not edit by hand.\n"
    "# This is the project's default build image. cup keeps its FROM base and the\n"
    "# apt packages of registered third-party dependencies in sync; `cup docker build`\n"
    "# versions and tags it, and `cup compiler verify` compiles the project in it.\n#\n";

// third_party_file is where registrations are recorded for the project's
// build tool: third_party/CMakeLists.txt for CMake, third_party/third_party.mk
// for Make. apt_packages scans whichever, so Docker image sync works for both.
std::filesystem::path third_party_file(const project::Project& proj) {
    if (proj.uses_make()) {
        return proj.path("third_party", "third_party.mk");
    }
    return proj.path("third_party", "CMakeLists.txt");
}

std::string join(std::span<const std::string> parts, std::string_view sep) {
    std::string out;
    for (std::size_t i = 0; i < parts.size(); ++i) {
        if (i > 0) {
            out += sep;
        }
        out += parts[i];
    }
    return out;
}

std::vector<std::string_view> split_fields(std::string_view s) {
    std::vector<std::string_view> fields;
    std::size_t i = 0;
    while (i < s.size()) {
        while (i < s.size() && std::isspace(static_cast<unsigned char>(s[i]))) {
            ++i;
        }
        const std::size_t start = i;
        while (i < s.size() && !std::isspace(static_cast<unsigned char>(s[i]))) {
            ++i;
        }
        if (i > start) {
            fields.push_back(s.substr(start, i - start));
        }
    }
    return fields;
}

std::optional<std::string> read_whole_file(const std::filesystem::path& path) {
    std::ifstream in(path, std::ios::binary);
    if (!in) {
        return std::nullopt;
    }
    return std::string(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
}

std::string lower(std::string_view s) {
    std::string out(s);
    std::ranges::transform(out, out.begin(),
                           [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
    return out;
}

// --- sha256: cup's fingerprint for deciding whether an image's Dockerfile
// changed since its last build (buildImage's hashFile). A small, self
// contained FIPS 180-4 implementation rather than a new OpenSSL dependency —
// this is a change-detection checksum, not a security boundary, and cup's
// dependency list (toml++, Catch2, libcurl) stays unchanged. Verified against
// the empty-string, "abc" and NIST test vectors while porting.

constexpr std::array<std::uint32_t, 64> kSha256K{
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2};

constexpr std::uint32_t sha256_rotr(std::uint32_t x, int n) { return (x >> n) | (x << (32 - n)); }

std::array<unsigned char, 32> sha256(std::string_view data) {
    std::array<std::uint32_t, 8> h{0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
                                   0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19};
    std::vector<unsigned char> msg(data.begin(), data.end());
    const std::uint64_t bit_len = static_cast<std::uint64_t>(data.size()) * 8;
    msg.push_back(0x80);
    while (msg.size() % 64 != 56) {
        msg.push_back(0);
    }
    for (int i = 7; i >= 0; --i) {
        msg.push_back(static_cast<unsigned char>(bit_len >> (i * 8)));
    }

    for (std::size_t chunk = 0; chunk < msg.size(); chunk += 64) {
        std::array<std::uint32_t, 64> w{};
        for (int i = 0; i < 16; ++i) {
            w[i] = (std::uint32_t(msg[chunk + i * 4]) << 24) |
                   (std::uint32_t(msg[chunk + i * 4 + 1]) << 16) |
                   (std::uint32_t(msg[chunk + i * 4 + 2]) << 8) | std::uint32_t(msg[chunk + i * 4 + 3]);
        }
        for (int i = 16; i < 64; ++i) {
            const std::uint32_t s0 =
                sha256_rotr(w[i - 15], 7) ^ sha256_rotr(w[i - 15], 18) ^ (w[i - 15] >> 3);
            const std::uint32_t s1 =
                sha256_rotr(w[i - 2], 17) ^ sha256_rotr(w[i - 2], 19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16] + s0 + w[i - 7] + s1;
        }
        auto a = h[0];
        auto b = h[1];
        auto c = h[2];
        auto d = h[3];
        auto e = h[4];
        auto f = h[5];
        auto g = h[6];
        auto hh = h[7];
        for (int i = 0; i < 64; ++i) {
            const std::uint32_t s1 = sha256_rotr(e, 6) ^ sha256_rotr(e, 11) ^ sha256_rotr(e, 25);
            const std::uint32_t ch = (e & f) ^ (~e & g);
            const std::uint32_t temp1 = hh + s1 + ch + kSha256K[i] + w[i];
            const std::uint32_t s0 = sha256_rotr(a, 2) ^ sha256_rotr(a, 13) ^ sha256_rotr(a, 22);
            const std::uint32_t maj = (a & b) ^ (a & c) ^ (b & c);
            const std::uint32_t temp2 = s0 + maj;
            hh = g;
            g = f;
            f = e;
            e = d + temp1;
            d = c;
            c = b;
            b = a;
            a = temp1 + temp2;
        }
        h[0] += a;
        h[1] += b;
        h[2] += c;
        h[3] += d;
        h[4] += e;
        h[5] += f;
        h[6] += g;
        h[7] += hh;
    }
    std::array<unsigned char, 32> out{};
    for (int i = 0; i < 8; ++i) {
        out[i * 4] = static_cast<unsigned char>(h[i] >> 24);
        out[i * 4 + 1] = static_cast<unsigned char>(h[i] >> 16);
        out[i * 4 + 2] = static_cast<unsigned char>(h[i] >> 8);
        out[i * 4 + 3] = static_cast<unsigned char>(h[i]);
    }
    return out;
}

std::string sha256_hex(std::string_view data) {
    std::string out;
    out.reserve(64);
    for (const unsigned char b : sha256(data)) {
        out += std::format("{:02x}", b);
    }
    return out;
}

std::expected<std::string, error::Error> hash_file(const std::filesystem::path& path) {
    const auto content = read_whole_file(path);
    if (!content.has_value()) {
        return std::unexpected(error::Error(std::format("reading {}", path.string())));
    }
    return sha256_hex(*content);
}

}  // namespace

std::filesystem::path docker_image_dir(const project::Project& proj, std::string_view name) {
    return proj.path("docker", name);
}

std::filesystem::path dockerfile_path(const project::Project& proj, std::string_view name) {
    return docker_image_dir(proj, name) / "Dockerfile";
}

std::vector<std::string> apt_packages(const project::Project& proj) {
    const auto lines = scaffold::read_file_lines(third_party_file(proj));
    if (!lines.has_value()) {
        return {};
    }
    std::vector<std::string> pkgs;
    std::vector<std::string> seen;
    for (const auto& raw : *lines) {
        const auto idx = raw.find(kAptMarker);
        if (idx == std::string::npos) {
            continue;
        }
        for (const auto field : split_fields(std::string_view(raw).substr(idx + kAptMarker.size()))) {
            const std::string pkg(field);
            if (std::ranges::find(seen, pkg) == seen.end()) {
                seen.push_back(pkg);
                pkgs.push_back(pkg);
            }
        }
    }
    return pkgs;
}

std::string render_build_dockerfile(std::string_view base, std::span<const std::string> pkgs) {
    std::string out(kGeneratedDockerfileHeader);
    out += "FROM ";
    out += base;
    out += "\n";
    if (!pkgs.empty()) {
        out += "\nRUN apt-get update \\\n";
        out += "    && apt-get install -y --no-install-recommends \\\n";
        for (const auto& p : pkgs) {
            out += "        ";
            out += p;
            out += " \\\n";
        }
        out += "    && rm -rf /var/lib/apt/lists/*\n";
    }
    return out;
}

std::expected<void, error::Error> sync_default_build_image(const project::Project& proj) {
    const auto* def = proj.config.docker.default_image();
    if (def == nullptr) {
        return {};
    }
    const auto pkgs = apt_packages(proj);
    const std::string content = render_build_dockerfile(def->base, pkgs);
    const std::filesystem::path path = dockerfile_path(proj, def->name);

    if (const auto old = read_whole_file(path); old.has_value() && *old == content) {
        return {};
    }

    std::error_code ec;
    std::filesystem::create_directories(path.parent_path(), ec);
    if (ec) {
        return std::unexpected(
            error::Error(std::format("creating {}: {}", path.parent_path().string(), ec.message())));
    }
    std::ofstream out(path, std::ios::binary | std::ios::trunc);
    out << content;
    if (!out) {
        return std::unexpected(error::Error(std::format("writing {}", path.string())));
    }

    const std::string label = (std::filesystem::path("docker") / def->name / "Dockerfile").string();
    if (!pkgs.empty()) {
        ui::updated(std::format("{}  (apt: {})", label, join(pkgs, " ")));
    } else {
        ui::updated(label);
    }
    return {};
}

std::expected<std::string, error::Error> choose_image_tag(std::string_view repo) {
    auto tags = scaffold::docker_hub_tags(repo);
    if (!tags.has_value() || tags->values.empty()) {
        ui::skipped(std::format("could not list tags for {} — enter one manually", repo));
        return ui::text("image tag?", "latest", scaffold::validate_non_empty);
    }
    std::vector<std::string> list = tags->values;
    if (list.size() > 20) {
        list.resize(20);
    }
    return ui::select_one(std::format("image tag for {}?", repo), list, list[0]);
}

std::expected<std::string, error::Error> choose_base_image() {
    auto repo = ui::text("base image repository? (e.g. gcc, debian, silkeh/clang)", "",
                         scaffold::validate_non_empty);
    if (!repo.has_value()) {
        return std::unexpected(std::move(repo).error());
    }
    auto tag = choose_image_tag(*repo);
    if (!tag.has_value()) {
        return std::unexpected(std::move(tag).error());
    }
    return *repo + ":" + *tag;
}

std::expected<std::vector<project::DockerImage*>, error::Error> select_images(
    project::Project& proj, std::span<const std::string> args) {
    if (proj.config.docker.images.empty()) {
        return std::unexpected(
            error::Error("this project defines no docker images (create one with `cup docker new`)"));
    }
    if (!args.empty() && !args[0].empty()) {
        auto* img = proj.config.docker.find(args[0]);
        if (img == nullptr) {
            return std::unexpected(
                error::Error(std::format("no docker image named \"{}\" in this project", args[0])));
        }
        return std::vector<project::DockerImage*>{img};
    }
    std::vector<project::DockerImage*> out;
    out.reserve(proj.config.docker.images.size());
    for (auto& img : proj.config.docker.images) {
        out.push_back(&img);
    }
    return out;
}

int next_version(int cur, std::string_view old_hash, std::string_view new_hash) {
    if (cur > 0 && old_hash == new_hash) {
        return cur;
    }
    return cur + 1;
}

std::string image_tag(std::string_view name, int version) { return std::format("{}:{}", name, version); }

std::expected<void, error::Error> persist_config(const project::Project& proj) {
    if (auto wrote = project::write_config(proj.root, proj.config); !wrote.has_value()) {
        return wrote;
    }
    ui::updated(project::kMarker);
    return {};
}

std::expected<void, error::Error> docker_new(project::Project& proj) {
    auto name = ui::text("image name?", "", scaffold::validate_ident);
    if (!name.has_value()) {
        return std::unexpected(std::move(name).error());
    }
    const std::string lname = lower(*name);
    if (proj.config.docker.find(lname) != nullptr) {
        return std::unexpected(
            error::Error(std::format("an image named \"{}\" already exists in this project", lname)));
    }
    auto base = choose_base_image();
    if (!base.has_value()) {
        return std::unexpected(std::move(base).error());
    }
    if (auto wrote = scaffold::write_file(proj.root, dockerfile_path(proj, lname), "FROM " + *base + "\n");
        !wrote.has_value()) {
        return std::unexpected(std::move(wrote).error());
    }
    proj.config.docker.images.push_back(project::DockerImage{.name = lname, .base = *base});
    if (auto persisted = persist_config(proj); !persisted.has_value()) {
        return persisted;
    }
    ui::success("image " + lname + " created.");
    ui::next("cup docker build " + lname);
    return {};
}

std::expected<void, error::Error> build_image(const project::Project& proj, project::DockerImage& img) {
    if (img.is_default) {
        if (auto synced = sync_default_build_image(proj); !synced.has_value()) {
            return synced;
        }
    }
    const std::filesystem::path path = dockerfile_path(proj, img.name);
    if (!std::filesystem::is_regular_file(path)) {
        return std::unexpected(error::Error(
            std::format("image \"{}\" has no Dockerfile at {}", img.name,
                        (std::filesystem::path("docker") / img.name / "Dockerfile").string())));
    }
    auto hash = hash_file(path);
    if (!hash.has_value()) {
        return std::unexpected(std::move(hash).error());
    }
    img.version = next_version(img.version, img.hash, *hash);
    img.hash = *hash;
    const std::string versioned = image_tag(img.name, img.version);
    ui::running(std::format("building {} from {}", versioned, img.base));
    const std::vector<std::string> args{"build", "-t", versioned, "-t", img.name + ":latest",
                                        docker_image_dir(proj, img.name).string()};
    return run_shell(proj.root, "docker", args);
}

std::expected<void, error::Error> run_docker_build(project::Project& proj,
                                                    std::span<const std::string> args) {
    auto targets = select_images(proj, args);
    if (!targets.has_value()) {
        return std::unexpected(std::move(targets).error());
    }
    for (auto* img : *targets) {
        if (auto built = build_image(proj, *img); !built.has_value()) {
            return built;
        }
    }
    return persist_config(proj);
}

std::expected<void, error::Error> push_image(const project::Project& proj, std::string_view registry,
                                             const project::DockerImage& img) {
    const std::vector<std::string> tags{std::to_string(img.version), "latest"};
    for (const auto& tag : tags) {
        const std::string local = img.name + ":" + tag;
        const std::string remote = std::string(registry) + "/" + img.name + ":" + tag;
        if (auto tagged = run_shell(proj.root, "docker", std::vector<std::string>{"tag", local, remote});
            !tagged.has_value()) {
            return tagged;
        }
        if (auto pushed = run_shell(proj.root, "docker", std::vector<std::string>{"push", remote});
            !pushed.has_value()) {
            return pushed;
        }
    }
    return {};
}

std::expected<void, error::Error> run_docker_push(project::Project& proj,
                                                   std::span<const std::string> args) {
    auto targets = select_images(proj, args);
    if (!targets.has_value()) {
        return std::unexpected(std::move(targets).error());
    }
    for (auto* img : *targets) {
        if (img->version == 0) {
            return std::unexpected(error::Error(std::format(
                "image \"{}\" has not been built yet — run `cup docker build {}` first", img->name,
                img->name)));
        }
    }
    if (proj.config.docker.registry.empty()) {
        auto reg =
            ui::text("registry/namespace to push to? (e.g. docker.io/youruser)", "", scaffold::validate_non_empty);
        if (!reg.has_value()) {
            return std::unexpected(std::move(reg).error());
        }
        std::string trimmed = *reg;
        while (!trimmed.empty() && trimmed.back() == '/') {
            trimmed.pop_back();
        }
        proj.config.docker.registry = trimmed;
        if (auto persisted = persist_config(proj); !persisted.has_value()) {
            return persisted;
        }
    }
    const std::string reg = proj.config.docker.registry;
    for (auto* img : *targets) {
        if (auto pushed = push_image(proj, reg, *img); !pushed.has_value()) {
            return pushed;
        }
    }
    return {};
}

std::expected<void, error::Error> run_docker(std::span<const std::string> args) {
    auto proj = project::find();
    if (!proj.has_value()) {
        return std::unexpected(std::move(proj).error());
    }
    if (args.empty()) {
        return std::unexpected(error::Error("usage: cup docker <new|build|push> [name]"));
    }
    const std::string& sub = args[0];
    const std::span<const std::string> rest = args.subspan(1);
    if (sub == "new") {
        return docker_new(*proj);
    }
    if (sub == "build") {
        return run_docker_build(*proj, rest);
    }
    if (sub == "push") {
        return run_docker_push(*proj, rest);
    }
    return std::unexpected(
        error::Error(std::format("unknown `cup docker` subcommand \"{}\" (use: new, build, push)", sub)));
}

}
